### ISSUE TITLE
Local First Run Results in AttributeError Exception

### ISSUE THREAD

**Issue by jnishiyama** [MentatInnovations/datastream.io#23]
Hello when starting to test this out, I was immediately faced with the issue below.

```Loading the data...
Done.

data found from 2018-03-25 14:14:30 to 2018-03-26 05:49:05
Converting to milliseconds ...
Done
Adding time offset of 0.06 seconds
Setting speed to 1x
Done
Traceback (most recent call last):
  File ".../tryingdsio/dsio-env/bin/dsio", line 9, in <module>
    load_entry_point('dsio==0.1.0', 'console_scripts', 'dsio')()
  File ".../tryingdsio/dsio-env/src/dsio/dsio/main.py", line 155, in main
    cols=int(args.cols)
  File ".../tryingdsio/dsio-env/src/dsio/dsio/main.py", line 70, in restream_dataframe
    port=bokeh_port, update_queue=update_queue
  File ".../tryingdsio/dsio-env/src/dsio/dsio/dashboard/bokeh.py", line 74, in generate_dashboard
    if io_loop._running: # Assume we're in a Jupyter notebook
AttributeError: 'AsyncIOMainLoop' object has no attribute '_running'```

I'm not sure what the root cause of the issue is, but I have a non-breaking fix for myself that may also help other people. I will make a PR with the change.

Thank you!

**Comment by fransedo2018** [comment]
Hello, I have the same issue. I tried in different computers and operative systems (Windows 10 and ubuntu 14) with no success. Seems to be a problem with Bokeh but not sure. Any solution?

**Comment by HKby** [comment]
I have got the same issue while running the ELK platform

**Comment by jnishiyama** [comment]
@HKby Hey, not sure if it helps, but I have this PR open which fixed it for me: https://github.com/MentatInnovations/datastream.io/pull/24

**Comment by HKby** [comment]
@jnishiyama Cool! The bugs gone. However, I went to another bunch of bugs. :) hahahaha. Gonna fix those first.

**Comment by amkrous** [comment]
I have the same issue.

**Comment by robmarkcole** [comment]
+1 having this issue

**Comment by ffahri** [comment]
https://github.com/MentatInnovations/datastream.io/issues/28#issuecomment-401280534
@robmarkcole @amkrous
