### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by pruceuchiha** [MentatInnovations/datastream.io#28]
dsio --es-uri http://localhost:9200/ --kibana-uri http://localhost:5601/app/kibana data/cardata_sample.csv
Loading the data...
Done.

data found from 2013-05-24 23:51:37 to 2013-05-25 00:14:13
Converting to milliseconds ...
Done
Adding time offset of 1529302326.54 seconds
Setting speed to 1x
Done
Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\dsio-script.py", line 11, in <module>
    load_entry_point('dsio', 'console_scripts', 'dsio')()
  File "c:\windows\system32\src\dsio\dsio\main.py", line 155, in main
    cols=int(args.cols)
  File "c:\windows\system32\src\dsio\dsio\main.py", line 70, in restream_dataframe
    port=bokeh_port, update_queue=update_queue
  File "c:\windows\system32\src\dsio\dsio\dashboard\bokeh.py", line 74, in generate_dashboard
    if io_loop._running: # Assume we're in a Jupyter notebook
AttributeError: 'AsyncIOMainLoop' object has no attribute '_running'

**Comment by ffahri** [comment]
downgrade tornado to 4.5.3 should work

pip3 install tornado==4.5.3

**Comment by cpoptic** [comment]
downgraded to tornado 4.5.3 and still getting this same error with   datastream=0.5.19=pypi_0

**Comment by ghost** [comment]
downgrading did not fix the problem and has caused other conflicts.

**Comment by qianvera** [comment]
Making small change to source codes, it works! Changing function `io_loop._running` to `io_loop._running()` in bokeh.py, as shown in the screenshot below.
![image](https://user-images.githubusercontent.com/13497279/80057264-b47e1700-8558-11ea-8e6c-bae417607ba8.png)
