### ISSUE TITLE
TypeError: search() got an unexpected keyword argument 'doc_type'

### ISSUE THREAD

**Issue by AliAzG** [MentatInnovations/datastream.io#34]
I'm using docker-compose and exact versions of elasticsearch and kibana wrote in `docker-compose.yml`. but when I run `dsio --es data/cardata_sample.csv` I get the below error:
Traceback (most recent call last):
  File "/home/data1/Documents/dsio-env/bin/dsio", line 11, in <module>
    load_entry_point('dsio', 'console_scripts', 'dsio')()
  File "/home/data1/Documents/dsio-env/src/dsio/dsio/main.py", line 155, in main
    cols=int(args.cols)
  File "/home/data1/Documents/dsio-env/src/dsio/dsio/main.py", line 60, in restream_dataframe
    generate_kibana_dashboard(es_conn, sensors, index_name)
  File "/home/data1/Documents/dsio-env/src/dsio/dsio/dashboard/kibana.py", line 39, in generate_dashboard
    vis_list = visualizations.get_all() # list all visualizations
  File "/home/data1/Documents/dsio-env/lib/python3.6/site-packages/kibana_dashboard_api/visualizations.py", line 61, in get_all
    res = self.es.search(index=self.index, doc_type=self.doc_type, body={'query': {'match_all': {}}})
  File "/home/data1/Documents/dsio-env/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
TypeError: search() got an unexpected keyword argument 'doc_type'
Anybody else had the same issue?
How can I solve this?
Thanks in advance.

**Comment by AliAzG** [comment]
This issue solved my problem:
https://github.com/MentatInnovations/datastream.io/issues/33#issue-474978498
